api_login_check:
    path: /api/login_check

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /apidoc


app_api_v1:
    type: rest
    prefix: /api/v1/
    resource: "routing/routing_api_v1.yml"