export const USER_LOGIN_ATTEMPT = 'USER_LOGIN_ATTEMPT'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAILED = 'USER_LOGIN_FAILED'

export const USER_SIGNUP_ATTEMPT = 'USER_SIGNUP_ATTEMPT'
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS'
export const USER_SIGNUP_FAILED = 'USER_SIGNUP_FAILED'

export const USER_LOGGED_OUT = 'USER_LOGGED_OUT'
