export const USER_LOGIN_ATTEMPT = 'USER_LOGIN_ATTEMPT'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAILED = 'USER_LOGIN_FAILED'

export const USER_SIGNUP_ATTEMPT = 'USER_SIGNUP_ATTEMPT'
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS'
export const USER_SIGNUP_FAILED = 'USER_SIGNUP_FAILED'

export const USER_LOGGED_OUT = 'USER_LOGGED_OUT'


export const ACTIVITY_START_ATTEMPT = 'ACTIVITY_START_ATTEMPT'
export const ACTIVITY_START_SUCCESS = 'ACTIVITY_START_SUCCESS'
export const ACTIVITY_START_FAILED = 'ACTIVITY_START_FAILED'

export const ACTIVITY_STOP_ATTEMPT = 'ACTIVITY_STOP_ATTEMPT'
export const ACTIVITY_STOP_SUCCESS = 'ACTIVITY_STOP_SUCCESS'
export const ACTIVITY_STOP_FAILED = 'ACTIVITY_STOP_FAILED'